name: 'Docker Build'
description: 'Build the docker image using Dockerfile'

inputs:
  image:
    required: true
  tag:
    required: true
  context:
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Docker build
      shell: bash
      run: docker build -t ${{ inputs.image }}:${{ inputs.tag }} -t ${{ inputs.image }}:latest  ${{ inputs.context }}